apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  USERNAME: {{ .Values.secrets.username.value | b64enc }}
  PASSWORD: {{ .Values.secrets.password.value | b64enc }}
  DB_NAME: {{ .Values.secrets.dbName.value | b64enc }}
  DB_URL: {{ .Values.secrets.dbUrl.value | b64enc }}
  APP_SECRET: {{ .Values.secrets.appSecret.value | b64enc }}
