name: Pre-merge checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  commit:
    name: Check conventional commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    continue-on-error: false
    timeout-minutes: 10
    steps:
      - name: check if PR title follows conventional commits specs
        uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
